### ISSUE TITLE
links to calls in chart

### ISSUE THREAD

**Issue by MichaelChirico** [moodymudskipper/funflow#8]
motivating example:

```
view_flow(median)
```

![Screenshot 2019-10-21 at 12 05 15 PM](https://user-images.githubusercontent.com/7606389/67176049-0f448380-f3fb-11e9-80f3-0ea98911a488.png)

Would be great we could click the `UseMethod('median')` box and traverse the call more interactively. A bit tough to do statically because obv we don't have any input to `median` so we don't know the method, but there could be a landing page to `methods('median')` first.

**Comment by moodymudskipper** [comment]
I agree, that would be awesome. Expanding a node right in the function would be great too.

Do you think this is technically possible without writing an adhoc flowchart library? I don't know much js and nomnoml is static. Maybe there's some other library I could use.

**Comment by MichaelChirico** [comment]
Above my weightclass sadly :( It's definitely possible, but I don't know with what framework/libraries/how much refactoring effort it would take

**Comment by moodymudskipper** [comment]
Right now we can already see the function by calling : 

    flow_run(median(1:3))

This detects the appropriate method (stats::median.default here) and outlines the path taken by the execution

![image](https://user-images.githubusercontent.com/18351714/85640916-676c0d80-b68d-11ea-8d77-b83d86839291.png)

It's in progress, not much tested and doesn't support loops yet.

I think this answers the main issue.

Now for the wider point of interactivity and design, the package is based on nomlnoml and limited by its capacities but nomnoml is really the last step and any new js technology ported to R could be used quite easily. I chose nomnoml just because other available technologies would forbid some special characters with no way of escaping them, which is problematic to write code in these blocks.

So I'm closing this for now, and ready to reopen whenever a package of clickable flow diagrams comes up.
